# Generated by Django 5.1.7 on 2025-09-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_donation_contact_number_donation_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='location',
        ),
        migrations.AddField(
            model_name='park',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='park',
            name='features',
            field=models.TextField(),
        ),
    ]
