# Generated by Django 5.1.7 on 2025-09-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_park_location_park_latitude_park_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='park',
            name='features',
            field=models.TextField(help_text='Available features like walking trails, benches, etc.'),
        ),
    ]
