# Generated by Django 5.1.7 on 2025-09-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='dropoff_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='dropoff_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='dropoff_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
