# Generated by Django 5.1.7 on 2025-09-09 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_donation_dropoff_address_donation_dropoff_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='dropoff_address',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='dropoff_latitude',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='dropoff_longitude',
        ),
    ]
